apiVersion: v1
kind: Pod
metadata: 
  name: naresh-pod
  namespace: naresh-namespace 
  labels:
    tier: frontend
  annotations: 
    imageregistry: https://hub.docker.com/
spec:
  containers:
   - name: naresh-nginx
     image: nginx
     ports:
     - containerPort: 80 