apiVersion: v1
kind: Pod
metadata:
    name: naresh-pod1
    labels:
      stage: dev
      env: dev
    annotations:
      imageregistry: https://hub.docker.com/
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    resources:
      requests:
        cpu: 60m
        memory: 60Mi
      limits:
        cpu: 100m
        memory: 100Mi  

    env:
    - name: course
      valueFrom:
        configMapKeyRef:
            name: san-nar-config
            key: course
    
     # env:
    # - name: course
    #   valueFrom:
    #     configMapKeyRef:
    #       name: naresh-config
    #       key: course
    

    # envFrom:
    # - configMapRef:
    #       name: san-nar-config

    # env:
    # - name: course
    #   value: devops
    # - name: status
    #   value: learning  
