apiVersion: v1
kind: Pod
metadata:
    name: naresh-pod1
    labels:
      stage: dev
      env: dev
    annotations:
      imageregistry: https://hub.docker.com/
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    env:
      name: nar
      valueFrom:
        configMapKeyRef:
            name: san-nar-config
            key: course
    
     # env:
    # - name: course
    #   valueFrom:
    #     configMapKeyRef:
    #       name: naresh-config
    #       key: course
    

    # envFrom:
    # - configMapRef:
    #       name: san-nar-config

    # env:
    # - name: course
    #   value: devops
    # - name: status
    #   value: learning  
